name: data_hub
version: "1.0.0"
profile: data_hub

config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_hub:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      dimensions:
        +materialized: table
        +schema: marts
      facts:
        +materialized: table
        +schema: marts
      reports:
        +materialized: table
        +schema: reports
