data_hub:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST', 'localhost') }}"
      port: "{{ env_var('PGPORT', '5432') | int }}"
      user: "{{ env_var('PGUSER', 'datahub') }}"
      password: "{{ env_var('PGPASSWORD', 'datahub') }}"
      dbname: "{{ env_var('PGDATABASE', 'datahub') }}"
      schema: public
      threads: 4
