// ---------------------------
// This file was generated by Nango (v0.69.46)
// You can version this file
// ---------------------------

/**
 * ! ** DEPRECATION NOTICE **
 * ! This file will stop being generated in future versions of nango.
 * ! For access to function types, please export types directly from your code.
 * ! You can leverage `zod.infer` to generate types from your zod schemas.
 * ! See the official zod documentation: https://zod.dev/basics?id=inferring-types
 */

export interface Opportunity {
  id: string;
  Id: string;
  Name: string;
  Amount: number | null;
  StageName: string;
  IsClosed: boolean;
  IsWon: boolean;
  CloseDate: string;
  CreatedDate: string;
  LastModifiedDate: string;
  ForecastCategoryName: string | null;
  Probability: number | null;
  Type: string | null;
  LeadSource: string | null;
  OwnerId: string;
  Account: {  Name: string | null;
  Industry: string | null;
  AnnualRevenue: number | null;} | null;
  Owner: {  Name: string | null;
  Email: string | null;};
  OpportunityContactRoles: {  records: ({  Id: string;
  ContactId: string;
  Role: string | null;
  IsPrimary: boolean;
  Contact: {  Email: string | null;};})[];} | null;
};

export type SyncMetadata_salesforce_fetchopportunities = void

export interface OpportunityHistory {
  id: string;
  Id: string;
  OpportunityId: string;
  StageName: string | null;
  Amount: number | null;
  CloseDate: string;
  Probability: number | null;
  CreatedDate: string;
  CreatedById: string;
};

export type SyncMetadata_salesforce_fetchopportunityhistory = void

export interface Task {
  id: string;
  Id: string;
  Subject: string | null;
  Status: string | null;
  ActivityDate: string | null;
  CreatedDate: string;
  WhoId: string | null;
  WhatId: string | null;
  OwnerId: string;
  TaskSubtype: string | null;
  CallType: string | null;
  CallDurationInSeconds: number | null;
  CallDisposition: string | null;
  Who: {  Email: string | null;} | null;
  Owner: {  Name: string | null;
  Email: string | null;};
};

export type SyncMetadata_salesforce_fetchtasks = void

export interface Event {
  id: string;
  Id: string;
  Subject: string | null;
  StartDateTime: string;
  EndDateTime: string;
  DurationInMinutes: number | null;
  ActivityDate: string | null;
  CreatedDate: string;
  WhoId: string | null;
  WhatId: string | null;
  OwnerId: string;
  EventSubtype: string | null;
  Who: {  Email: string | null;} | null;
  Owner: {  Name: string | null;
  Email: string | null;};
};

export type SyncMetadata_salesforce_fetchevents = void

export interface Contact {
  id: string;
  Id: string;
  FirstName: string | null;
  LastName: string;
  Email: string | null;
  Phone: string | null;
  MobilePhone: string | null;
  Title: string | null;
  Department: string | null;
  AccountId: string | null;
  OwnerId: string;
  MailingCity: string | null;
  MailingState: string | null;
  MailingCountry: string | null;
  LeadSource: string | null;
  CreatedDate: string;
  LastModifiedDate: string;
  Account: {  Name: string | null;
  Industry: string | null;} | null;
  Owner: {  Name: string | null;
  Email: string | null;};
};

export type SyncMetadata_salesforce_fetchcontacts = void

export interface Account {
  id: string;
  Id: string;
  Name: string;
  Type: string | null;
  Industry: string | null;
  Description: string | null;
  Website: string | null;
  Phone: string | null;
  AnnualRevenue: number | null;
  NumberOfEmployees: number | null;
  OwnerId: string;
  ParentId: string | null;
  BillingCity: string | null;
  BillingState: string | null;
  BillingCountry: string | null;
  Rating: string | null;
  CreatedDate: string;
  LastModifiedDate: string;
  Owner: {  Name: string | null;
  Email: string | null;};
  Parent: {  Name: string | null;} | null;
};

export type SyncMetadata_salesforce_fetchaccounts = void

export interface User {
  id: string;
  Id: string;
  Name: string;
  FirstName: string | null;
  LastName: string;
  Email: string;
  Username: string;
  Alias: string | null;
  Title: string | null;
  Department: string | null;
  Division: string | null;
  CompanyName: string | null;
  IsActive: boolean;
  ManagerId: string | null;
  ProfileId: string;
  UserRoleId: string | null;
  CreatedDate: string;
  LastModifiedDate: string;
  LastLoginDate: string | null;
  Manager: {  Name: string | null;
  Email: string | null;} | null;
  Profile: {  Name: string | null;} | null;
};

export type SyncMetadata_salesforce_fetchusers = void
