// ---------------------------
// This file was generated by Nango (v0.69.45)
// You can version this file
// ---------------------------

/**
 * ! ** DEPRECATION NOTICE **
 * ! This file will stop being generated in future versions of nango.
 * ! For access to function types, please export types directly from your code.
 * ! You can leverage `zod.infer` to generate types from your zod schemas.
 * ! See the official zod documentation: https://zod.dev/basics?id=inferring-types
 */

export interface GithubIssue {
  id: string;
  owner: string;
  repo: string;
  issue_number: number;
  title: string;
  state: string;
  author: string;
  author_id: number;
  body: string;
  date_created: string;
  date_last_modified: string;
};

export type SyncMetadata_github_fetchissues = void

export interface ActionInput_github_createissue {
  id: string;
  owner: string;
  repo: string;
  issue_number: number;
  title: string;
  state: string;
  author: string;
  author_id: number;
  body: string;
  date_created: string;
  date_last_modified: string;
};

export type ActionOutput_github_createissue = void

export interface GithubRepoFile {
  id: string;
  name: string;
  url: string;
  last_modified_date: Date;
};

export interface SyncMetadata_github_listfiles {
  owner: string;
  repo: string;
  branch: string;
};

export interface Opportunity {
  id: string;
  Id: string;
  Name: string;
  Amount: number | null;
  StageName: string;
  IsClosed: boolean;
  IsWon: boolean;
  CloseDate: string;
  CreatedDate: string;
  LastModifiedDate: string;
  ForecastCategoryName: string | null;
  Probability: number | null;
  Type: string | null;
  LeadSource: string | null;
  OwnerId: string;
  Account: {  Name: string | null;
  Industry: string | null;
  AnnualRevenue: number | null;} | null;
  Owner: {  Name: string | null;
  Email: string | null;};
  OpportunityContactRoles: {  records: ({  Id: string;
  ContactId: string;
  Role: string | null;
  IsPrimary: boolean;
  Contact: {  Email: string | null;};})[];} | null;
};

export type SyncMetadata_salesforce_fetchopportunities = void

export interface OpportunityHistory {
  id: string;
  Id: string;
  OpportunityId: string;
  StageName: string | null;
  Amount: number | null;
  CloseDate: string;
  Probability: number | null;
  CreatedDate: string;
  CreatedById: string;
};

export type SyncMetadata_salesforce_fetchopportunityhistory = void

export interface Task {
  id: string;
  Id: string;
  Subject: string | null;
  Status: string | null;
  ActivityDate: string | null;
  CreatedDate: string;
  WhoId: string | null;
  WhatId: string | null;
  OwnerId: string;
  TaskSubtype: string | null;
  CallType: string | null;
  CallDurationInSeconds: number | null;
  CallDisposition: string | null;
  Who: {  Email: string | null;} | null;
  Owner: {  Name: string | null;
  Email: string | null;};
};

export type SyncMetadata_salesforce_fetchtasks = void

export interface Event {
  id: string;
  Id: string;
  Subject: string | null;
  StartDateTime: string;
  EndDateTime: string;
  DurationInMinutes: number | null;
  ActivityDate: string | null;
  CreatedDate: string;
  WhoId: string | null;
  WhatId: string | null;
  OwnerId: string;
  EventSubtype: string | null;
  Who: {  Email: string | null;} | null;
  Owner: {  Name: string | null;
  Email: string | null;};
};

export type SyncMetadata_salesforce_fetchevents = void
